# Copyright (C) 1991-2013 Altera Corporation
# Your use of Altera Corporation's design tools, logic functions 
# and other software and tools, and its AMPP partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License 
# Subscription Agreement, Altera MegaCore Function License 
# Agreement, or other applicable license agreement, including, 
# without limitation, that your use is for the sole purpose of 
# programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the 
# applicable agreement for further details.

# Quartus II 64-Bit Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Full Version
# File: D:\Spira_Heaven\0-My Works\3D_Displayer\VHDL\Pin\PIN.tcl
# Generated on: Tue Apr 01 22:11:18 2014

package require ::quartus::project

set_location_assignment PIN_T1 -to inclk
set_location_assignment PIN_U10 -to ddr2_addr[0]
set_location_assignment PIN_Y6 -to ddr2_addr[1]
set_location_assignment PIN_T16 -to ddr2_addr[2]
set_location_assignment PIN_R14 -to ddr2_addr[3]
set_location_assignment PIN_AA4 -to ddr2_addr[4]
set_location_assignment PIN_T11 -to ddr2_addr[5]
set_location_assignment PIN_AB5 -to ddr2_addr[6]
set_location_assignment PIN_T14 -to ddr2_addr[7]
set_location_assignment PIN_AA3 -to ddr2_addr[8]
set_location_assignment PIN_U13 -to ddr2_addr[9]
set_location_assignment PIN_V6 -to ddr2_addr[10]
set_location_assignment PIN_AB3 -to ddr2_addr[11]
set_location_assignment PIN_U14 -to ddr2_addr[12]
set_location_assignment PIN_U7 -to ddr2_bank[0]
set_location_assignment PIN_AB10 -to ddr2_bank[1]
set_location_assignment PIN_T9 -to ddr2_bank[2]
set_location_assignment PIN_R15 -to n_cas
set_location_assignment PIN_U8 -to cke
set_location_assignment PIN_AA17 -to ddr2_clk
set_location_assignment PIN_AB17 -to ddr2_n_clk
set_location_assignment PIN_Y17 -to n_cs
set_location_assignment PIN_R16 -to odt
set_location_assignment PIN_T10 -to n_ras
set_location_assignment PIN_V7 -to n_we
set_location_assignment PIN_V5 -to ldm
set_location_assignment PIN_AA7 -to udm
set_location_assignment PIN_AA10 -to ldm_2
set_location_assignment PIN_AA16 -to udm_2
set_location_assignment PIN_V8 -to ddr2_data[0]
set_location_assignment PIN_W6 -to ddr2_data[1]
set_location_assignment PIN_W8 -to ddr2_data[2]
set_location_assignment PIN_W7 -to ddr2_data[3]
set_location_assignment PIN_Y3 -to ddr2_data[4]
set_location_assignment PIN_Y7 -to ddr2_data[5]
set_location_assignment PIN_AA5 -to ddr2_data[6]
set_location_assignment PIN_U9 -to ddr2_data[7]
set_location_assignment PIN_AA9 -to ddr2_data[8]
set_location_assignment PIN_AB8 -to ddr2_data[9]
set_location_assignment PIN_Y10 -to ddr2_data[10]
set_location_assignment PIN_AA8 -to ddr2_data[11]
set_location_assignment PIN_AB7 -to ddr2_data[12]
set_location_assignment PIN_V11 -to ddr2_data[13]
set_location_assignment PIN_Y8 -to ddr2_data[14]
set_location_assignment PIN_W10 -to ddr2_data[15]
set_location_assignment PIN_AB15 -to ddr2_data[16]
set_location_assignment PIN_W13 -to ddr2_data[17]
set_location_assignment PIN_AB14 -to ddr2_data[18]
set_location_assignment PIN_AA13 -to ddr2_data[19]
set_location_assignment PIN_AB13 -to ddr2_data[20]
set_location_assignment PIN_AA14 -to ddr2_data[21]
set_location_assignment PIN_U12 -to ddr2_data[22]
set_location_assignment PIN_AA15 -to ddr2_data[23]
set_location_assignment PIN_T15 -to ddr2_data[24]
set_location_assignment PIN_V15 -to ddr2_data[25]
set_location_assignment PIN_W17 -to ddr2_data[26]
set_location_assignment PIN_AB16 -to ddr2_data[27]
set_location_assignment PIN_V14 -to ddr2_data[28]
set_location_assignment PIN_AB20 -to ddr2_data[29]
set_location_assignment PIN_W15 -to ddr2_data[30]
set_location_assignment PIN_AB18 -to ddr2_data[31]
set_location_assignment PIN_V10 -to ldqs
set_location_assignment PIN_AB9 -to udqs
set_location_assignment PIN_Y13 -to ldqs_2
set_location_assignment PIN_V13 -to udqs_2
set_location_assignment PIN_D13 -to usb_data[0]
set_location_assignment PIN_E14 -to usb_data[1]
set_location_assignment PIN_E13 -to usb_data[2]
set_location_assignment PIN_C13 -to usb_data[3]
set_location_assignment PIN_F13 -to usb_data[4]
set_location_assignment PIN_E12 -to usb_data[5]
set_location_assignment PIN_F11 -to usb_data[6]
set_location_assignment PIN_E11 -to usb_data[7]
set_location_assignment PIN_D10 -to usb_data[8]
set_location_assignment PIN_C10 -to usb_data[9]
set_location_assignment PIN_C8 -to usb_data[10]
set_location_assignment PIN_E9 -to usb_data[11]
set_location_assignment PIN_C7 -to usb_data[12]
set_location_assignment PIN_F8 -to usb_data[13]
set_location_assignment PIN_C6 -to usb_data[14]
set_location_assignment PIN_E7 -to usb_data[15]
set_location_assignment PIN_B21 -to pc_rqu
set_location_assignment PIN_D20 -to sloe
set_location_assignment PIN_D19 -to slrd
set_location_assignment PIN_D17 -to slwr
set_location_assignment PIN_D15 -to usb_empty
set_location_assignment PIN_C15 -to usb_full
set_location_assignment PIN_C21 -to usb_clk
set_location_assignment PIN_E16 -to usb_fifoadr[0]
set_location_assignment PIN_C17 -to usb_fifoadr[1]
set_location_assignment PIN_W19 -to pktend
set_location_assignment PIN_Y2 -to en_col_b_1
set_location_assignment PIN_W2 -to en_col_b_2
set_location_assignment PIN_V2 -to en_col_b_3
set_location_assignment PIN_U2 -to data_buffer_b[39]
set_location_assignment PIN_T7 -to data_buffer_b[38]
set_location_assignment PIN_P5 -to data_buffer_b[37]
set_location_assignment PIN_M5 -to data_buffer_b[36]
set_location_assignment PIN_V3 -to data_buffer_b[35]
set_location_assignment PIN_P6 -to data_buffer_b[34]
set_location_assignment PIN_N7 -to data_buffer_b[33]
set_location_assignment PIN_M8 -to data_buffer_b[32]
set_location_assignment PIN_R2 -to data_buffer_b[31]
set_location_assignment PIN_P2 -to data_buffer_b[30]
set_location_assignment PIN_N2 -to data_buffer_b[29]
set_location_assignment PIN_M2 -to data_buffer_b[28]
set_location_assignment PIN_T4 -to data_buffer_b[27]
set_location_assignment PIN_P4 -to data_buffer_b[26]
set_location_assignment PIN_N5 -to data_buffer_b[25]
set_location_assignment PIN_L8 -to data_buffer_b[24]
set_location_assignment PIN_L6 -to data_buffer_b[23]
set_location_assignment PIN_L7 -to data_buffer_b[22]
set_location_assignment PIN_J2 -to data_buffer_b[21]
set_location_assignment PIN_H2 -to data_buffer_b[20]
set_location_assignment PIN_F1 -to data_buffer_b[19]
set_location_assignment PIN_K7 -to data_buffer_b[18]
set_location_assignment PIN_J3 -to data_buffer_b[17]
set_location_assignment PIN_H7 -to data_buffer_b[16]
set_location_assignment PIN_G4 -to data_buffer_b[15]
set_location_assignment PIN_G9 -to data_buffer_b[14]
set_location_assignment PIN_H10 -to data_buffer_b[13]
set_location_assignment PIN_E6 -to data_buffer_b[12]
set_location_assignment PIN_G8 -to data_buffer_b[11]
set_location_assignment PIN_E10 -to data_buffer_b[10]
set_location_assignment PIN_G11 -to data_buffer_b[9]
set_location_assignment PIN_B3 -to data_buffer_b[8]
set_location_assignment PIN_B4 -to data_buffer_b[7]
set_location_assignment PIN_B5 -to data_buffer_b[6]
set_location_assignment PIN_B6 -to data_buffer_b[5]
set_location_assignment PIN_B7 -to data_buffer_b[4]
set_location_assignment PIN_B8 -to data_buffer_b[3]
set_location_assignment PIN_B9 -to data_buffer_b[2]
set_location_assignment PIN_B10 -to data_buffer_b[1]
set_location_assignment PIN_AA1 -to en_col_a_1
set_location_assignment PIN_Y1 -to en_col_a_2
set_location_assignment PIN_W1 -to en_col_a_3
set_location_assignment PIN_V1 -to data_buffer_a[39]
set_location_assignment PIN_U1 -to data_buffer_a[38]
set_location_assignment PIN_R6 -to data_buffer_a[37]
set_location_assignment PIN_N6 -to data_buffer_a[36]
set_location_assignment PIN_M6 -to data_buffer_a[35]
set_location_assignment PIN_R7 -to data_buffer_a[34]
set_location_assignment PIN_P7 -to data_buffer_a[33]
set_location_assignment PIN_M7 -to data_buffer_a[32]
set_location_assignment PIN_R1 -to data_buffer_a[31]
set_location_assignment PIN_P1 -to data_buffer_a[30]
set_location_assignment PIN_N1 -to data_buffer_a[29]
set_location_assignment PIN_M1 -to data_buffer_a[28]
set_location_assignment PIN_R5 -to data_buffer_a[27]
set_location_assignment PIN_P3 -to data_buffer_a[26]
set_location_assignment PIN_M4 -to data_buffer_a[25]
set_location_assignment PIN_M3 -to data_buffer_a[24]
set_location_assignment PIN_K8 -to data_buffer_a[23]
set_location_assignment PIN_J1 -to data_buffer_a[22]
set_location_assignment PIN_H1 -to data_buffer_a[21]
set_location_assignment PIN_F2 -to data_buffer_a[20]
set_location_assignment PIN_E1 -to data_buffer_a[19]
set_location_assignment PIN_J7 -to data_buffer_a[18]
set_location_assignment PIN_J4 -to data_buffer_a[17]
set_location_assignment PIN_J6 -to data_buffer_a[16]
set_location_assignment PIN_G7 -to data_buffer_a[15]
set_location_assignment PIN_G10 -to data_buffer_a[14]
set_location_assignment PIN_G5 -to data_buffer_a[13]
set_location_assignment PIN_F7 -to data_buffer_a[12]
set_location_assignment PIN_F9 -to data_buffer_a[11]
set_location_assignment PIN_F10 -to data_buffer_a[10]
set_location_assignment PIN_H11 -to data_buffer_a[9]
set_location_assignment PIN_A3 -to data_buffer_a[8]
set_location_assignment PIN_A4 -to data_buffer_a[7]
set_location_assignment PIN_A5 -to data_buffer_a[6]
set_location_assignment PIN_A6 -to data_buffer_a[5]
set_location_assignment PIN_A7 -to data_buffer_a[4]
set_location_assignment PIN_A8 -to data_buffer_a[3]
set_location_assignment PIN_A9 -to data_buffer_a[2]
set_location_assignment PIN_A10 -to data_buffer_a[1]
set_location_assignment PIN_U19 -to sensor
set_location_assignment PIN_N19 -to en_col_c_1
set_location_assignment PIN_M19 -to en_col_c_2
set_location_assignment PIN_A13 -to en_col_c_3
set_location_assignment PIN_R19 -to en_row_a
set_location_assignment PIN_A20 -to en_row_c[1]
set_location_assignment PIN_R18 -to en_row_c[0]
set_location_assignment PIN_P20 -to data_buffer_c[39]
set_location_assignment PIN_N20 -to data_buffer_c[38]
set_location_assignment PIN_T17 -to data_buffer_c[37]
set_location_assignment PIN_R17 -to data_buffer_c[36]
set_location_assignment PIN_N17 -to data_buffer_c[35]
set_location_assignment PIN_AA21 -to data_buffer_c[34]
set_location_assignment PIN_Y22 -to data_buffer_c[33]
set_location_assignment PIN_W22 -to data_buffer_c[32]
set_location_assignment PIN_V22 -to data_buffer_c[31]
set_location_assignment PIN_U22 -to data_buffer_c[30]
set_location_assignment PIN_R22 -to data_buffer_c[29]
set_location_assignment PIN_P22 -to data_buffer_c[28]
set_location_assignment PIN_N22 -to data_buffer_c[27]
set_location_assignment PIN_M22 -to data_buffer_c[26]
set_location_assignment PIN_G16 -to data_buffer_c[25]
set_location_assignment PIN_H17 -to data_buffer_c[24]
set_location_assignment PIN_F16 -to data_buffer_c[23]
set_location_assignment PIN_L22 -to data_buffer_c[22]
set_location_assignment PIN_K22 -to data_buffer_c[21]
set_location_assignment PIN_J22 -to data_buffer_c[20]
set_location_assignment PIN_H22 -to data_buffer_c[19]
set_location_assignment PIN_F22 -to data_buffer_c[18]
set_location_assignment PIN_E22 -to data_buffer_c[17]
set_location_assignment PIN_D22 -to data_buffer_c[16]
set_location_assignment PIN_B22 -to data_buffer_c[15]
set_location_assignment PIN_K18 -to data_buffer_c[14]
set_location_assignment PIN_J18 -to data_buffer_c[13]
set_location_assignment PIN_H20 -to data_buffer_c[12]
set_location_assignment PIN_G18 -to data_buffer_c[11]
set_location_assignment PIN_F19 -to data_buffer_c[10]
set_location_assignment PIN_B20 -to data_buffer_c[9]
set_location_assignment PIN_B19 -to data_buffer_c[8]
set_location_assignment PIN_B18 -to data_buffer_c[7]
set_location_assignment PIN_B17 -to data_buffer_c[6]
set_location_assignment PIN_B16 -to data_buffer_c[5]
set_location_assignment PIN_B15 -to data_buffer_c[4]
set_location_assignment PIN_B14 -to data_buffer_c[3]
set_location_assignment PIN_B13 -to data_buffer_c[2]
set_location_assignment PIN_A19 -to data_buffer_c[1]
set_location_assignment PIN_C19 -to usb_in
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_addr[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_bank[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_bank[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_bank[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to n_cas
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to cke
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_clk
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_n_clk
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to n_cs
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to odt
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to n_ras
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to n_we
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ldm
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to udm
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ldm_2
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to udm_2
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[13]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[14]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[15]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[16]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[17]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[18]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[19]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[20]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[21]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[22]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[23]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[24]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[25]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[26]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[27]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[28]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[29]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[30]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2_data[31]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ldqs
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to udqs
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ldqs_2
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to udqs_2
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_addr[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_bank[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_bank[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2_bank[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to n_cas
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to cke
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_clk
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_n_clk
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to n_cs
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to odt
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to n_ras
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to n_we
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ldm
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to udm
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ldm_2
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to udm_2
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[19]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[20]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[21]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[22]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[23]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[24]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[25]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[26]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[27]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[28]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[29]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[30]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2_data[31]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ldqs
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to udqs
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ldqs_2
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to udqs_2
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[8]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[9]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[10]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[11]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[12]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[13]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[14]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[15]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[16]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[17]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[18]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[19]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[20]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[21]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[22]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[23]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[24]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[25]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[26]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[27]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[28]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[29]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[30]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[31]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_data[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ldqs_2
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to udqs
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to udqs_2
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ldm
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ldm_2
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to udm
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to udm_2
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_clk
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ddr2_n_clk
set_instance_assignment -name OUTPUT_ENABLE_GROUP 42 -to ldqs
set_location_assignment PIN_D6 -to bluetooth_data[3]
set_location_assignment PIN_C3 -to bluetooth_data[1]
set_location_assignment PIN_G3 -to bluetooth_rqu
set_location_assignment PIN_E3 -to bluetooth_reset
set_location_assignment PIN_D2 -to bluetooth_data[0]
set_location_assignment PIN_E4 -to bluetooth_ack
set_location_assignment PIN_C4 -to bluetooth_data[2]
set_location_assignment PIN_A16 -to data_buffer_b[0]
set_location_assignment PIN_A15 -to data_buffer_a[0]
set_location_assignment PIN_A18 -to en_row_b
set_location_assignment PIN_A17 -to data_buffer_c[0]
set_instance_assignment -name SLEW_RATE 1 -to bluetooth_ack
set_instance_assignment -name SLEW_RATE 1 -to bluetooth_reset
set_instance_assignment -name SLEW_RATE 1 -to cke
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[0]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[1]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[2]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[3]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[4]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[5]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[6]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[7]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[8]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[9]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[10]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[11]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[12]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[13]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[14]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[15]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[16]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[17]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[18]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[19]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[20]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[21]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[22]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[23]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[24]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[25]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[26]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[27]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[28]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[29]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[30]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[31]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[32]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[33]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[34]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[35]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[36]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[37]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[38]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_a[39]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[0]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[1]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[2]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[3]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[4]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[5]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[6]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[7]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[8]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[9]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[10]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[11]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[12]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[13]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[14]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[15]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[16]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[17]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[18]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[19]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[20]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[21]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[22]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[23]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[24]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[25]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[26]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[27]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[28]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[29]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[30]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[31]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[32]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[33]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[34]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[35]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[36]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[37]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[38]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_b[39]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[0]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[1]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[2]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[3]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[4]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[5]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[6]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[7]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[8]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[9]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[10]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[11]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[12]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[13]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[14]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[15]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[16]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[17]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[18]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[19]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[20]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[21]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[22]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[23]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[24]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[25]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[26]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[27]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[28]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[29]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[30]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[31]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[32]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[33]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[34]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[35]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[36]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[37]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[38]
set_instance_assignment -name SLEW_RATE 1 -to data_buffer_c[39]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[0]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[1]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[2]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[3]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[4]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[5]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[6]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[7]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[8]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[9]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[10]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[11]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_addr[12]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_bank[0]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_bank[1]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_bank[2]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_clk
set_instance_assignment -name SLEW_RATE 1 -to ddr2_n_clk
set_instance_assignment -name SLEW_RATE 1 -to en_col_a_1
set_instance_assignment -name SLEW_RATE 1 -to en_col_a_2
set_instance_assignment -name SLEW_RATE 1 -to en_col_a_3
set_instance_assignment -name SLEW_RATE 1 -to en_col_b_1
set_instance_assignment -name SLEW_RATE 1 -to en_col_b_2
set_instance_assignment -name SLEW_RATE 1 -to en_col_b_3
set_instance_assignment -name SLEW_RATE 1 -to en_col_c_1
set_instance_assignment -name SLEW_RATE 1 -to en_col_c_2
set_instance_assignment -name SLEW_RATE 1 -to en_col_c_3
set_instance_assignment -name SLEW_RATE 1 -to en_row_a
set_instance_assignment -name SLEW_RATE 1 -to en_row_b
set_instance_assignment -name SLEW_RATE 1 -to en_row_c[0]
set_instance_assignment -name SLEW_RATE 1 -to en_row_c[1]
set_instance_assignment -name SLEW_RATE 1 -to ldm
set_instance_assignment -name SLEW_RATE 1 -to ldm_2
set_instance_assignment -name SLEW_RATE 1 -to n_cas
set_instance_assignment -name SLEW_RATE 1 -to n_cs
set_instance_assignment -name SLEW_RATE 1 -to n_ras
set_instance_assignment -name SLEW_RATE 1 -to n_we
set_instance_assignment -name SLEW_RATE 1 -to odt
set_instance_assignment -name SLEW_RATE 1 -to pktend
set_instance_assignment -name SLEW_RATE 1 -to sloe
set_instance_assignment -name SLEW_RATE 1 -to slrd
set_instance_assignment -name SLEW_RATE 1 -to slwr
set_instance_assignment -name SLEW_RATE 1 -to udm
set_instance_assignment -name SLEW_RATE 1 -to udm_2
set_instance_assignment -name SLEW_RATE 1 -to usb_clk
set_instance_assignment -name SLEW_RATE 1 -to usb_fifoadr[0]
set_instance_assignment -name SLEW_RATE 1 -to usb_fifoadr[1]
set_instance_assignment -name SLEW_RATE 1 -to bluetooth_data[0]
set_instance_assignment -name SLEW_RATE 1 -to bluetooth_data[1]
set_instance_assignment -name SLEW_RATE 1 -to bluetooth_data[2]
set_instance_assignment -name SLEW_RATE 1 -to bluetooth_data[3]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[0]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[1]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[2]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[3]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[4]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[5]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[6]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[7]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[8]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[9]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[10]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[11]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[12]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[13]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[14]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[15]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[16]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[17]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[18]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[19]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[20]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[21]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[22]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[23]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[24]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[25]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[26]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[27]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[28]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[29]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[30]
set_instance_assignment -name SLEW_RATE 1 -to ddr2_data[31]
set_instance_assignment -name SLEW_RATE 1 -to ldqs
set_instance_assignment -name SLEW_RATE 1 -to ldqs_2
set_instance_assignment -name SLEW_RATE 1 -to udqs
set_instance_assignment -name SLEW_RATE 1 -to udqs_2
set_instance_assignment -name SLEW_RATE 1 -to usb_data[0]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[1]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[2]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[3]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[4]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[5]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[6]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[7]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[8]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[9]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[10]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[11]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[12]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[13]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[14]
set_instance_assignment -name SLEW_RATE 1 -to usb_data[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to bluetooth_ack
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to bluetooth_reset
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[19]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[20]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[21]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[22]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[23]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[24]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[25]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[26]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[27]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[28]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[29]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[30]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[31]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[32]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[33]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[34]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[35]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[36]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[37]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[38]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_a[39]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[19]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[20]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[21]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[22]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[23]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[24]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[25]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[26]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[27]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[28]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[29]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[30]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[31]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[32]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[33]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[34]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[35]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[36]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[37]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[38]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_b[39]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[19]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[20]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[21]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[22]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[23]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[24]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[25]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[26]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[27]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[28]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[29]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[30]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[31]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[32]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[33]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[34]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[35]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[36]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[37]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[38]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to data_buffer_c[39]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_a_1
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_a_2
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_a_3
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_b_1
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_b_2
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_b_3
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_c_1
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_c_2
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_col_c_3
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_row_a
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_row_b
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_row_c[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to en_row_c[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to pktend
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to sloe
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to slrd
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to slwr
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_clk
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_fifoadr[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_fifoadr[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to bluetooth_data[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to bluetooth_data[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to bluetooth_data[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to bluetooth_data[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to usb_data[15]
